### PR TITLE
Add decompress plugin

### PR DESCRIPTION
**Pull request by luii**
Added a new decompression plugin

### CODE REVIEW

**Comment by deepsweet** [comment]
Thanks 😍

I'll fix CI and tweak code a bit here and there. Most likely today.

**Comment by deepsweet** [comment]
What do you think about the following API?

```js
sequence(
  find('dir/*.tar'),
  decompress({ /* options */ }),
  write('extracted/')
)
```

I see that it's possible to delegate writing functionality to `write` plugin and even have something like `rename` or whatever plugins in between (I know that there is a `map` option in `decompress` lib itself, but this flow doesn't feel natural in case of Start). Actually the only option we need from `decompress` is an array of plugins.

**Comment by luii** [comment]
Approved! I like this approach.

**Comment by luii** [comment]
How do you plan to do it?

**Comment by deepsweet** [comment]
Sorry for the long reply. I'll merge this almost as is for now. That idea with `write` plugin requires a lot more work than expected, and I don't want to block this PR.

In a few words Start is not fully ready to work effectively with binary (probably huge) data the way it works with text files. It's going to be changed soon, I found the elegant solution that needs to be tested.

**Comment by deepsweet** [comment]
Published as `@start/plugin-unpack` 🎉 Please let me know if there are some issues, I'll add real tests later.

**Comment by luii** [comment]
Okay!

**Pull request merged**
